# Generated by Django 3.0.6 on 2020-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='adı')),
                ('last_name', models.CharField(max_length=30, verbose_name='soyadı')),
                ('father_name', models.CharField(blank=True, max_length=30, verbose_name='atasının adı')),
                ('date_of_birth', models.DateField(verbose_name='doğum tarixi')),
                ('gender', models.CharField(choices=[('K', 'kişi'), ('Q', 'qadın')], max_length=1, verbose_name='cinsi')),
                ('family_status', models.CharField(choices=[('E', 'evli'), ('S', 'subay')], max_length=1, verbose_name='ailə vəziyyəti')),
                ('education', models.CharField(blank=True, choices=[('A', 'ali'), ('O', 'orta'), ('Y', 'yoxdur')], max_length=1, verbose_name='təhsili')),
                ('passport_number', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='vəsiqənin seriya nömrəsi')),
                ('registered_place', models.CharField(blank=True, max_length=45, verbose_name='qeydiyyat yeri')),
            ],
            options={
                'verbose_name': 'İşçi',
                'verbose_name_plural': 'İşçilər',
            },
        ),
    ]
