# Generated by Django 3.0.6 on 2020-06-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20200611_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldWorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250, verbose_name='işlədiyi şirkətin adı')),
                ('position', models.CharField(max_length=45, verbose_name='vəzifəsi')),
                ('started', models.DateField(verbose_name='işə başladiğı tarix')),
                ('finished', models.DateField(verbose_name='işdən çıxma tarixi')),
                ('cause', models.TextField(verbose_name='işdən çıxma səbəbi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee', verbose_name='işçi')),
            ],
            options={
                'verbose_name': 'köhnə iş yeri',
                'verbose_name_plural': 'köhnə iş yerləri',
            },
        ),
    ]
