# Generated by Django 3.0.6 on 2020-06-19 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_oldworkplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldworkplace',
            options={'verbose_name': 'Köhnə iş yeri', 'verbose_name_plural': 'Köhnə iş yerləri'},
        ),
        migrations.RemoveField(
            model_name='oldworkplace',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='oldworkplace',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='oldworkplace',
            name='started',
        ),
        migrations.AddField(
            model_name='oldworkplace',
            name='finished_work',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='İşdən çıxma tarixi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oldworkplace',
            name='reason_of_leave',
            field=models.CharField(default='', max_length=255, verbose_name='İşdən çıxma səbəbi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oldworkplace',
            name='started_work',
            field=models.DateField(default='2020-06-19', verbose_name='İşə başladığı tarix'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ünvanı'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city_of_residence',
            field=models.CharField(blank=True, max_length=45, verbose_name='Yaşadığı şəhər/kənd'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Əlaqə nömrəsi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_number2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Əlaqə nömrəsi əlavə'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Doğum tarixi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('A', 'Ali'), ('O', 'Orta'), ('Y', 'Yoxdur')], max_length=1, verbose_name='Təhsili'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='family_status',
            field=models.CharField(choices=[('E', 'Evli'), ('S', 'Subay')], max_length=1, verbose_name='Ailə vəziyyəti'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Atasının adı'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('K', 'Kişi'), ('Q', 'Qadın')], max_length=1, verbose_name='Cinsi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Soyadı'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Vəsiqənin seriya nömrəsi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Şəkli'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='registered_place',
            field=models.CharField(blank=True, max_length=45, verbose_name='Qeydiyyatda olduğu yer'),
        ),
        migrations.AlterField(
            model_name='oldworkplace',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='İşlədiyi şirkətin adı'),
        ),
        migrations.AlterField(
            model_name='oldworkplace',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee', verbose_name='İşçi'),
        ),
        migrations.AlterField(
            model_name='oldworkplace',
            name='position',
            field=models.CharField(max_length=45, verbose_name='Vəzifəsi'),
        ),
        migrations.AlterModelTable(
            name='oldworkplace',
            table='hr_old_work_place',
        ),
    ]
