# Generated by Django 3.0.6 on 2020-06-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_branch_company_department_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_work', models.DateField(verbose_name='İşə başladığı tarix')),
                ('salary', models.IntegerField(verbose_name='Aylıq əmək haqqı')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Branch', verbose_name='Filial')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Company', verbose_name='Şirkət')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department', verbose_name='Şöbə')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee', verbose_name='İşçi')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Position', verbose_name='İxtisas')),
            ],
            options={
                'verbose_name': 'Hazırki iş yeri',
                'verbose_name_plural': 'Hazırki iş yerləri',
                'db_table': 'hr_current_job',
            },
        ),
    ]
