# Generated by Django 3.0.6 on 2020-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20200711_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='type_of_vacation',
            field=models.CharField(choices=[('1type', 'Əmək məzuniyyəti'), ('2type', 'Sosisal məzuniyyət'), ('3type', 'Ödənişsiz məzuniyyət')], default='1type', max_length=5, verbose_name='Məzuniyyətin növü'),
        ),
    ]
